// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMS.Infrastructure;

#nullable disable

namespace SMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112053924_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClassroomUser", b =>
                {
                    b.Property<int>("ClassroomsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ClassroomsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ClassroomUsers", (string)null);
                });

            modelBuilder.Entity("SMS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("SchoolID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SMS.Models.school_related.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomID");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("SMS.Models.school_related.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolID");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1A",
                            SchoolID = 1
                        });
                });

            modelBuilder.Entity("SMS.Models.school_related.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "A leading school providing quality education.",
                            Name = "Greenwood High School"
                        });
                });

            modelBuilder.Entity("SMS.Models.user_lists.ListOfUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolID");

                    b.ToTable("ListOfUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sujoy2k4@gmail.com",
                            Role = 0,
                            SchoolID = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "kineticelement1@gmail.com",
                            Role = 1,
                            SchoolID = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "teacher@school.com",
                            Role = 2,
                            SchoolID = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "student@school.com",
                            Role = 3,
                            SchoolID = 1
                        });
                });

            modelBuilder.Entity("ClassroomUser", b =>
                {
                    b.HasOne("SMS.Models.school_related.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Models.User", b =>
                {
                    b.HasOne("SMS.Models.school_related.Attendance", null)
                        .WithMany("Users")
                        .HasForeignKey("AttendanceId");

                    b.HasOne("SMS.Models.school_related.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("School");
                });

            modelBuilder.Entity("SMS.Models.school_related.Attendance", b =>
                {
                    b.HasOne("SMS.Models.school_related.Classroom", "Classroom")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassroomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("SMS.Models.school_related.Classroom", b =>
                {
                    b.HasOne("SMS.Models.school_related.School", "School")
                        .WithMany("Classrooms")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SMS.Models.user_lists.ListOfUsers", b =>
                {
                    b.HasOne("SMS.Models.school_related.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SMS.Models.school_related.Attendance", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SMS.Models.school_related.Classroom", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("SMS.Models.school_related.School", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
